from __future__ import annotations

from enum import Enum


class COSLayer(str, Enum):
    PROVIDER_BOUNDARY = "L0_PROVIDER_BOUNDARY"
    CAPABILITY = "L1_CAPABILITY"
    INTENT_ROUTING = "L2_INTENT_ROUTING"
    POLICY = "L3_POLICY"
    CLAIM_LEASE = "L4_CLAIM_LEASE"
    INVOCATION = "L5_INVOCATION"
    SIDE_EFFECT = "L6_SIDE_EFFECT"
    RECEIPT = "L7_RECEIPT"
    EVENT_EVIDENCE = "L8_EVENT_EVIDENCE"
    REDUCER_OUTBOX = "L9_REDUCER_OUTBOX"
    DURABLE_STATE = "L10_DURABLE_STATE"
    PROJECTION_INDEX = "L11_PROJECTION_INDEX"
    SESSION_CONTEXT = "L12_SESSION_CONTEXT"
    CHANNEL_GATEWAY = "L13_CHANNEL_GATEWAY"
    DEVICE_RUNTIME = "L14_DEVICE_RUNTIME"
    MEMORY_KNOWLEDGE = "L15_MEMORY_KNOWLEDGE"
    OBSERVABILITY_ECONOMICS = "L16_OBSERVABILITY_ECONOMICS"
    LEARNING_EVAL = "L17_LEARNING_EVAL"
    GOVERNANCE_SECURITY = "L18_GOVERNANCE_SECURITY"
    EMBODIMENT_EXPERIENCE = "L19_EMBODIMENT_EXPERIENCE"


class IntegrationDecision(str, Enum):
    KEEP_NATIVE = "KEEP_NATIVE"
    ADAPT = "ADAPT"
    CANONICALIZE = "CANONICALIZE"
    MERGE_STATE = "MERGE_STATE"
    REWRITE_LATER = "REWRITE_LATER"
